[tools]
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
# opencode = "latest"
ripgrep = "latest"
# rust = "latest"
xh = "latest"
# zig = "latest"
zoxide = "latest"
"npm:opencode-ai" = { version = "latest" }
"npm:@anthropic-ai/claude-code" = { version = "latest" }
"npm:bun" = { version = "latest" }
