[tools]
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
# rust = "latest"
xh = "latest"
zoxide = "latest"
# "npm:opencode-ai" = { version = "latest" }
# "npm:@anthropic-ai/claude-code" = { version = "latest" }
"npm:bun" = { version = "latest" }
pipx = "latest"
dotnet = "latest"
